wordings = {
    "mandatory_field": "Ce champ est obligatoire",
    "invalid_request": "Requête invalide",

    "faq": "FAQ",
    "new_message_from": "Nouveau message de la part de {}",
    "message_sent": "Ton message a bien été envoyé.",
    "contact": "Contact",
    "anonymous": "Anonyme",

    "account_validated": "Ton compte est à présent validé.",
    "password_updated": "Ton mot de passe a été mis à jour.",
    "password_change": "Changement de mot de passe",
    "password_reset": "Réinitialisation du mot de passe",
    "password_reset_email_sent": "Un email contenant des instructions pour réinitialiser ton mot de passe t'a été envoyé. Si tu n'as pas reçu d'email, vérifie dans ton dossier de spams et assure toi d'avoir rentré la bonne adresse mail.",
    "username_already_used": "Ce nom d'utilisateur est déjà pris",
    "email_already_used": "Cet email existe déjà",
    "invalid_confirmation_link": "Ce lien de confirmation est invalide ou a expiré.",
    "invalid_password": "Mot de passe incorrect",
    "invalid_credentials": "Identifiants incorrects",
    "invalid_reset_password_link": "L'adresse mail entrée ne correspond pas au lien de réinitialisation envoyé.",
    "login": "Connexion",
    "signup": "Inscription",
    "login_confirmed": "Tu es à présent connecté.",
    "email_address_confirmation": "Confirmation de ton adresse mail",
    "confirmation_email_sent": "Un email de confirmation t'a été envoyé.",
    "new_user_signup": "Nouvel inscrit",
    "users": "Utilisateurs",

    "settings": "Paramètres",
    "notification_preferences_updated": "Tes préférences de notifications ont été mises à jour",
    "email_notifications_activated": "Notifications par mail activées",

    "choose_a_category": "Choisir une catégorie",
    "choose_a_player": "Choisir un joueur",

    "player_already_exists": "Ce joueur existe déjà",
    "player_in_use": "Ce joueur ne peut pas être supprimé car il apparait dans le tableau d'au moins un tournoi ({})",
    "player_created": "Le joueur {} a été créé",
    "player_updated": "Le joueur {} a été mis à jour",
    "player_deleted": "Le joueur {} a été supprimé",
    "first_name": "Prénom",
    "last_name": "Nom",

    "create_a_tournament": "Créer un tournoi",
    "tournament_created": "Le tournoi {} a été créé",
    "tournament_updated": "Le tournoi {} a été mis à jour",
    "tournament_draw": "{} – Tableau",
    "tournament_draw_created": "Le tableau du tournoi {} a été créé",
    "tournament_draw_updated": "Le tableau du tournoi {} a été modifié",
    "tournament_draw_has_been_modified": "Tableau du tournoi {} modifié",
    "tournaments": "Tournois",

    "registrations_opened": "Les inscriptions au tournoi sont ouvertes",
    "registrations_closed": "Les inscriptions au tournoi sont closes",
    "tournament_closed": "Le tournoi a bien été clos",
    "registrations_opened_this_week": "Les tournois de la semaine sont ouverts aux inscriptions !",
    "participants_already_notified": "La notification par mail a déjà été envoyée pour tous les tournois de la semaine",
    "participants_notified": "Les participants ont été notifiés par mail de l'ouverture des tournois de la semaine",

    "not_allowed_to_register": "Tu n'es pas autorisé à t'inscrire à ce tournoi, soit car tu es déjà inscrit à un autre tournoi cette semaine, soit car les inscriptions sont fermées.",
    "not_allowed_to_make_a_forecast": "Tu n'es pas autorisé à faire un pronostic pour ce tournoi",
    "not_allowed_to_withdraw": "Tu ne peux plus te retirer de ce tournoi",
    "not_registered_yet": "Tu n'es pas inscrit à ce tournoi",
    "registration_confirmed": "Tu es bien inscrit au tournoi {}",
    "withdrawal_confirmed": "Tu es bien désinscrit du tournoi {}",
    "forecast_confirmed": "Ton pronostic a bien été pris en compte.",
    "invalid_forecast": "Ce pronostic est invalide.",

    "ranking": "Classement",
    "rankings": "Classements",
    "monthly_rankings": "Classements par mois",
    "choose_a_week": "Choisir une semaine",
    "choose_a_month": "Choisir un mois",
    "week": "Semaine",
    "month": "Mois",
    "profile_of": "Profil de {}"
}
